version: '3'

services:
  master:
    image: registry.cn-hangzhou.aliyuncs.com/yywh/hadoop:1.9.1
    hostname: hadoop_master
    container_name: hadoop_master
    networks:
     - hadoop
    ports:
     - '50070:50070'
     - '8088:8088'
     - '8030-8033:8030-8033'
     - '29000:9000'
    deploy:
      placement:
        constraints:
         - node.role == manage
    command: >
      bash -c "service ssh start
      && ./start-hadoop.sh
      && ping www.baidu.com"
  slave1:
    image: registry.cn-hangzhou.aliyuncs.com/yywh/hadoop:1.9.1
    hostname: hadoop_slave1
    container_name: hadoop_slave1
    networks:
     - hadoop
    deploy:
      placement:
        constraints:
        - node.hostname == dev-01
    command: >
      bash -c "service ssh start
      && ping www.baidu.com"
  slave2:
    image: registry.cn-hangzhou.aliyuncs.com/yywh/hadoop:1.9.1
    hostname: hadoop_slave2
    container_name: hadoop_slave2
    networks:
     - hadoop
    deploy:
      placement:
        constraints:
        - node.hostname == dev-02
    command: >
      bash -c "service ssh start
      && ping www.baidu.com"
networks:
  hadoop:
    driver: overlay