version: '3'

services:
  master:
    image: jybaby1027/hadoop:v1
    hostname: hadoop_master
    container_name: hadoop_master
    networks:
     - hadoop
    ports:
     - '50070:50070'
     - '8088:8088'
     - '8030-8033:8030-8033'
     - '29000:9000'
    deploy:
      placement:
        constraints:
         - node.role == manage
    command: ./start-hadoop.sh
  slave1:
    image: jybaby1027/hadoop:v1
    hostname: hadoop_slave1
    container_name: hadoop_slave1
    networks:
     - hadoop
    deploy:
      placement:
        constraints:
        - node.hostname == dev-01
  slave2:
    image: jybaby1027/hadoop:v1
    hostname: hadoop_slave2
    container_name: hadoop_slave2
    networks:
     - hadoop
    deploy:
      placement:
        constraints:
        - node.hostname == dev-02
networks:
  hadoop:
    driver: overlay