version: '3'

services:
  master:
    image: jybaby1027/hadoop:v1
    hostname: hadoop-master
    container_name: hadoop-master
    domainname: hadoop
    networks:
     - hadoop
    ports:
     - '50070:50070'
     - '8088:8088'
     - '8030-8033:8030-8033'
     - '29000:9000'
    deploy:
      placement:
        constraints:
         - node.role == manage
    command: ./start-hadoop.sh
  slave1:
    image: jybaby1027/hadoop:v1
    hostname: hadoop-slave1
    container_name: hadoop-slave1
    domainname: hadoop
    networks:
     - hadoop
    deploy:
      placement:
        constraints:
        - node.namenode == dev-01
  slave2:
    image: jybaby1027/hadoop:v1
    hostname: hadoop-slave2
    container_name: hadoop-slave2
    domainname: hadoop
    networks:
     - hadoop
    deploy:
      placement:
        constraints:
        - node.namenode == dev-02
networks:
  hadoop:
    driver: overlay